import type { Style, StyleKey } from './types';

export const STYLES: Record<StyleKey, Style> = {
  front_matter_title: {
    key: 'front_matter_title',
    name: 'Front matter titel',
    description: 'En titel til en sektion i forordet, f.eks. "Forord".',
    className: 'text-2xl font-bold text-gray-800 dark:text-gray-200 mt-6 mb-3',
    jatsTag: 'title',
    nestingParentJats: 'sec', // No direct <book-front> in JATS, maps to a sec in <front>
    bitsTag: 'title',
    nestingParentBits: 'book-part', // A book-part inside book-front
    level: 0,
    attributes: { 'book-part-type': 'preface' },
    matterType: 'front',
    allowedDocumentTypes: ['book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#1a202c',
      fontWeight: '700',
      fontSize: 24,
    },
  },
  back_matter_title: {
    key: 'back_matter_title',
    name: 'Back matter titel',
    description: 'En titel til en sektion i efterordet, f.eks. "Appendiks".',
    className: 'text-2xl font-bold text-gray-800 dark:text-gray-200 mt-6 mb-3',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'book-part',
    level: 0,
    attributes: { 'book-part-type': 'appendix' },
    matterType: 'back',
    allowedDocumentTypes: ['book'],
     visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#1a202c',
      fontWeight: '700',
      fontSize: 24,
    },
  },
  del: {
    key: 'del',
    name: 'Deltitel',
    description: 'En overordnet del af bogen, som indeholder kapitler.',
    className: 'text-4xl font-black text-gray-800 dark:text-gray-200 mt-6 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'book-part',
    level: 0,
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#1a202c', // Dark gray
      fontWeight: '900', // Black
      fontSize: 36, // 4xl
      lineHeight: 1.2,
    },
  },
  kapitel: {
    key: 'kapitel',
    name: 'Kapiteltitel',
    description: 'En overskrift til et hovedkapitel i en bog.',
    className: 'text-xl-relative font-bold text-gray-900 dark:text-gray-100 mt-8 mb-4',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'chapter',
    level: 1,
    attributes: {},
    matterType: 'chapter',
    allowedDocumentTypes: ['book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#1a202c', // Dark gray
      fontWeight: '700', // Bold
      fontSize: 28,
      lineHeight: 1.3,
    },
  },
  abstract_heading: {
    key: 'abstract_heading',
    name: 'Resume overskrift',
    description: 'Overskriften til resuméet.',
    className: 'text-lg font-semibold text-gray-800 dark:text-gray-300 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'abstract',
    bitsTag: 'title',
    nestingParentBits: 'abstract',
    attributes: {},
    matterType: 'front',
    allowedDocumentTypes: ['journal'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748', // Gray-800
      fontWeight: '600', // Semibold
      fontSize: 20,
      lineHeight: 1.4,
    },
  },
  abstract: {
    key: 'abstract',
    name: 'Abstrakt',
    description: 'Et kort resumé af indholdet.',
    className: 'text-md italic text-gray-600 dark:text-gray-400 border-l-4 border-blue-200 dark:border-blue-800 pl-4 py-2',
    jatsTag: 'p',
    nestingParentJats: 'abstract',
    bitsTag: 'p',
    nestingParentBits: 'abstract',
    attributes: {},
    matterType: 'front',
    allowedDocumentTypes: ['journal'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#4a5568', // Gray-600
      fontWeight: '400', // Normal
      fontSize: 18,
      lineHeight: 1.5,
      fontStyle: 'italic',
    },
  },
  section_heading_1: {
    key: 'section_heading_1',
    name: 'Overskrift 1',
    description: 'Overskrift til en hovedsektion (Niveau 1).',
    className: 'text-2xl font-semibold text-gray-800 dark:text-gray-200 mt-6 mb-2 border-b border-gray-300 dark:border-gray-600 pb-1',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 2,
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748',
      fontWeight: '600',
      fontSize: 24,
      lineHeight: 1.4,
    },
  },
  section_heading_2: {
    key: 'section_heading_2',
    name: 'Overskrift 2',
    description: 'Overskrift til en undersektion (Niveau 2).',
    className: 'text-xl font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 3,
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748',
      fontWeight: '600',
      fontSize: 20,
      lineHeight: 1.4,
    },
  },
  section_heading_3: {
    key: 'section_heading_3',
    name: 'Overskrift 3',
    description: 'Overskrift til en under-undersektion (Niveau 3).',
    className: 'text-lg font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 4,
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748',
      fontWeight: '600',
      fontSize: 18,
      lineHeight: 1.4,
    },
  },
  section_heading_4: {
    key: 'section_heading_4',
    name: 'Overskrift 4',
    description: 'Overskrift til en under-under-undersektion (Niveau 4).',
    className: 'text-md font-semibold text-gray-800 dark:text-gray-200 mt-3 mb-1',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 5,
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 1.4,
    },
  },
  section_heading_5: {
    key: 'section_heading_5',
    name: 'Overskrift 5',
    description: 'Overskrift til en under-under-under-undersektion (Niveau 5).',
    className: 'text-md font-medium text-gray-800 dark:text-gray-200 mt-3 mb-1',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 6,
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 1.4,
    },
  },
  body: {
    key: 'body',
    name: 'Brødtekst',
    description: 'Standard afsnitstekst.',
    className: 'text-base leading-relaxed mb-1',
    jatsTag: 'p',
    bitsTag: 'p',
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151',
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 1.6,
    },
  },
  petit: {
    key: 'petit',
    name: 'Petit',
    description: 'Mindre tekst til noter eller indskud.',
    className: 'text-sm leading-relaxed mb-4',
    jatsTag: 'p',
    bitsTag: 'p',
    attributes: { 'content-type': 'brevier' },
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#4b5563',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 1.6,
    },
  },
  
  caption: {
    key: 'caption',
    name: 'Billedtekst',
    description: 'En titel eller forklaring til en figur eller tabel.',
    className: 'text-sm text-gray-500 dark:text-gray-400 mt-2 text-center',
    jatsTag: 'p',
    nestingParentJats: 'caption',
    bitsTag: 'p',
    nestingParentBits: 'caption',
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#6b7280',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 1.4,
      textAlign: 'center',
    },
  },
  table: {
    key: 'table',
    name: 'Tabel',
    description: 'Indsæt en struktureret tabel med rækker og kolonner.',
    className: '',
    jatsTag: 'table-wrap',
    bitsTag: 'table-wrap',
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151',
      fontSize: 16,
    },
  },
  image: {
    key: 'image',
    name: 'Billede',
    description: 'Indsæt et billede med billedtekst og kilde.',
    className: '',
    jatsTag: 'fig',
    bitsTag: 'fig',
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151',
      fontSize: 16,
    },
  },
  ordered_list_item: {
    key: 'ordered_list_item',
    name: 'Opstillingsliste',
    description: 'Et element i en nummereret liste (1, 2, 3...).',
    className: 'text-base leading-relaxed',
    jatsTag: 'list-item',
    bitsTag: 'list-item',
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    defaultListAttributes: { style: 'decimal' },
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151',
      fontSize: 16,
      lineHeight: 1.5,
    },
  },
  unordered_list_item: {
    key: 'unordered_list_item',
    name: 'Punktopstilling',
    description: 'Et element i en punktliste (•, o, -...).',
    className: 'text-base leading-relaxed',
    jatsTag: 'list-item',
    bitsTag: 'list-item',
    attributes: {},
    matterType: 'body',
    allowedDocumentTypes: ['journal', 'book'],
    defaultListAttributes: { style: 'disc' },
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151',
      fontSize: 16,
      lineHeight: 1.5,
    },
  },
};

export const emptyStyle: Omit<Style, 'key'> = {
  name: '',
  description: '',
  className: '',
  jatsTag: 'p',
  bitsTag: 'p',
  nestingParentJats: '',
  nestingParentBits: '',
  level: undefined, 
  attributes: {},
  matterType: 'body',
  allowedDocumentTypes: ['journal', 'book'],
  visualSettings: {
    fontFamily: 'Nunito, sans-serif',
    color: '#374151',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 1.42,
    fontStyle: 'normal',
    textTransform: 'none',
    textDecoration: 'none',
    textAlign: 'left',
    textShadow: 'none',
    wordBreak: 'normal',
    letterSpacing: 0,
    wordSpacing: 0,
    columnCount: 1,
    direction: 'ltr',
  },
};