// Fix: Corrected import path.
import type { Style, StyleKey } from './types';

export const STYLES: Record<StyleKey, Style> = {
  del: {
    key: 'del',
    name: 'Deltitel',
    description: 'En overordnet del af bogen, som indeholder kapitler.',
    className: 'text-4xl font-black text-gray-800 dark:text-gray-200 mt-6 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'book-part',
    level: 0,
    attributes: {},
    matterType: 'body', // For JATS, would map to sec in body. For BITS, this is like a high-level division within body.
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#1a202c', // Dark gray
      fontWeight: '900', // Black
      fontSize: 36, // 4xl
      lineHeight: 1.2,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  kapitel: {
    key: 'kapitel',
    name: 'Kapiteltitel',
    description: 'En overskrift til et hovedkapitel i en bog.',
    className: 'text-xl-relative font-bold text-gray-900 dark:text-gray-100 mt-8 mb-4',
    jatsTag: 'title', // JATS does not have a chapter concept, maps to a top-level sec
    nestingParentJats: 'sec',
    bitsTag: 'title', // The parent tag will be <chapter>
    nestingParentBits: 'chapter',
    level: 1, // Top-level for hierarchy
    attributes: {},
    matterType: 'chapter', // Special type for BITS chapters
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#1a202c', // Dark gray
      fontWeight: '700', // Bold
      fontSize: 28,
      lineHeight: 1.3,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  abstract_heading: {
    key: 'abstract_heading',
    name: 'Resume overskrift',
    description: 'Overskriften til resuméet.',
    className: 'text-lg font-semibold text-gray-800 dark:text-gray-300 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'abstract',
    bitsTag: 'title',
    nestingParentBits: 'abstract',
    attributes: {},
    matterType: 'front', // Part of front matter (abstract)
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748', // Gray-800
      fontWeight: '600', // Semibold
      fontSize: 20,
      lineHeight: 1.4,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  abstract: {
    key: 'abstract',
    name: 'Abstrakt',
    description: 'Et kort resumé af indholdet.',
    className: 'text-md italic text-gray-600 dark:text-gray-400 border-l-4 border-blue-200 dark:border-blue-800 pl-4 py-2',
    jatsTag: 'p',
    nestingParentJats: 'abstract',
    bitsTag: 'p',
    nestingParentBits: 'abstract',
    attributes: {},
    matterType: 'front', // Part of front matter (abstract)
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#4a5568', // Gray-600
      fontWeight: '400', // Normal
      fontSize: 18,
      lineHeight: 1.5,
      fontStyle: 'italic',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  section_heading_1: {
    key: 'section_heading_1',
    name: 'Overskrift 1',
    description: 'Overskrift til en hovedsektion (Niveau 1).',
    className: 'text-2xl font-semibold text-gray-800 dark:text-gray-200 mt-6 mb-2 border-b border-gray-300 dark:border-gray-600 pb-1',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 2,
    attributes: {},
    matterType: 'body', // Standard body matter heading
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748', // Gray-800
      fontWeight: '600', // Semibold
      fontSize: 24,
      lineHeight: 1.4,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  section_heading_2: {
    key: 'section_heading_2',
    name: 'Overskrift 2',
    description: 'Overskrift til en undersektion (Niveau 2).',
    className: 'text-xl font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 3,
    attributes: {},
    matterType: 'body',
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748', // Gray-800
      fontWeight: '600', // Semibold
      fontSize: 20,
      lineHeight: 1.4,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  section_heading_3: {
    key: 'section_heading_3',
    name: 'Overskrift 3',
    description: 'Overskrift til en under-undersektion (Niveau 3).',
    className: 'text-lg font-semibold text-gray-800 dark:text-gray-200 mt-4 mb-2',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 4,
    attributes: {},
    matterType: 'body',
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748', // Gray-800
      fontWeight: '600', // Semibold
      fontSize: 18,
      lineHeight: 1.4,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  section_heading_4: {
    key: 'section_heading_4',
    name: 'Overskrift 4',
    description: 'Overskrift til en under-under-undersektion (Niveau 4).',
    className: 'text-md font-semibold text-gray-800 dark:text-gray-200 mt-3 mb-1',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 5,
    attributes: {},
    matterType: 'body',
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748', // Gray-800
      fontWeight: '600', // Semibold
      fontSize: 16,
      lineHeight: 1.4,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  section_heading_5: {
    key: 'section_heading_5',
    name: 'Overskrift 5',
    description: 'Overskrift til en under-under-under-undersektion (Niveau 5).',
    className: 'text-md font-medium text-gray-800 dark:text-gray-200 mt-3 mb-1',
    jatsTag: 'title',
    nestingParentJats: 'sec',
    bitsTag: 'title',
    nestingParentBits: 'sec',
    level: 6,
    attributes: {},
    matterType: 'body',
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#2d3748', // Gray-800
      fontWeight: '500', // Medium
      fontSize: 16,
      lineHeight: 1.4,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  body: {
    key: 'body',
    name: 'Brødtekst',
    description: 'Standard afsnitstekst.',
    className: 'text-base leading-relaxed mb-1',
    jatsTag: 'p',
    bitsTag: 'p',
    attributes: {},
    matterType: 'body', // Default to body matter
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151', // Gray-700
      fontWeight: '400', // Normal
      fontSize: 16,
      lineHeight: 1.5,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  petit: {
    key: 'petit',
    name: 'Petit',
    description: 'Mindre tekst til noter eller indskud.',
    className: 'text-sm leading-relaxed mb-4',
    jatsTag: 'p',
    bitsTag: 'p',
    attributes: { 'content-type': 'brevier' },
    matterType: 'body', // Default to body matter
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#4b5563', // Gray-600
      fontWeight: '400', // Normal
      fontSize: 14,
      lineHeight: 1.6,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  
  caption: {
    key: 'caption',
    name: 'Billedtekst',
    description: 'En titel eller forklaring til en figur eller tabel.',
    className: 'text-sm text-gray-500 dark:text-gray-400 mt-2 text-center',
    jatsTag: 'p',
    nestingParentJats: 'caption',
    bitsTag: 'p',
    nestingParentBits: 'caption',
    attributes: {},
    matterType: 'body', // Captions typically appear within body matter figures/tables
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#6b7280', // Gray-500
      fontWeight: '400', // Normal
      fontSize: 14,
      lineHeight: 1.4,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'center',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  table: {
    key: 'table',
    name: 'Tabel',
    description: 'Indsæt en struktureret tabel med rækker og kolonner.',
    className: '', // Tables have their own complex styling
    jatsTag: 'table-wrap',
    bitsTag: 'table-wrap',
    attributes: {},
    matterType: 'body', // Tables typically appear within body matter
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151', // Gray-700
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 1.5,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  image: {
    key: 'image',
    name: 'Billede',
    description: 'Indsæt et billede med billedtekst og kilde.',
    className: '', // Images have their own complex styling
    jatsTag: 'fig',
    bitsTag: 'fig',
    attributes: {},
    matterType: 'body', // Images typically appear within body matter
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151', // Gray-700
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 1.5,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'center',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  ordered_list_item: {
    key: 'ordered_list_item',
    name: 'Opstillingsliste',
    description: 'Et element i en nummereret liste (1, 2, 3...).',
    className: 'text-base leading-relaxed',
    jatsTag: 'list-item',
    bitsTag: 'list-item',
    attributes: {},
    matterType: 'body',
    defaultListAttributes: { style: 'decimal' },
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151', // Gray-700
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 1.5,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
  unordered_list_item: {
    key: 'unordered_list_item',
    name: 'Punktopstilling',
    description: 'Et element i en punktliste (•, o, -...).',
    className: 'text-base leading-relaxed',
    jatsTag: 'list-item',
    bitsTag: 'list-item',
    attributes: {},
    matterType: 'body',
    defaultListAttributes: { style: 'disc' },
    visualSettings: {
      fontFamily: 'Nunito, sans-serif',
      color: '#374151', // Gray-700
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 1.5,
      fontStyle: 'normal',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'left',
      textShadow: 'none',
      wordBreak: 'normal',
      letterSpacing: 0,
      wordSpacing: 0,
      columnCount: 1,
      direction: 'ltr',
    },
  },
};

export const emptyStyle: Omit<Style, 'key'> = {
  name: '',
  description: '',
  className: '',
  jatsTag: 'p',
  bitsTag: 'p',
  nestingParentJats: '',
  nestingParentBits: '',
  level: undefined, 
  attributes: {},
  matterType: 'body', // Default for new styles
  visualSettings: { // Default visual settings for new styles
    fontFamily: 'Nunito, sans-serif',
    color: '#374151',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 1.42,
    fontStyle: 'normal',
    textTransform: 'none',
    textDecoration: 'none',
    textAlign: 'left',
    textShadow: 'none',
    wordBreak: 'normal',
    letterSpacing: 0,
    wordSpacing: 0,
    columnCount: 1,
    direction: 'ltr',
  },
};